#spring:
#  profiles: de
#npta:
#  db:
#    username: username (from application.yml)
#    password: password
#    url: test.db
#  jms:
#    username: JMSUsername (from application.yml)
#    password: JMSPassword
#    url: jms.test.db
